version: "3"

services:
  app:
    image: ghcr.io/${GITHUB_REPO_LOWER}/stocktok_laravel:${IMAGE_TAG:-latest}
    container_name: stocktok_app_${IMAGE_TAG:-latest}
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=stocktok_${IMAGE_TAG:-latest}
      - DB_USERNAME=root
      - DB_PASSWORD=${DB_PASSWORD:-secretpassword}
      - APP_ENV=${IMAGE_TAG:-production}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your_default_key}
    restart: always
    depends_on:
      - database

  database:
    image: mysql:8.0
    container_name: stocktok_db_${IMAGE_TAG:-latest}
    volumes:
      - database:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-secretpassword}
      - MYSQL_DATABASE=stocktok_${IMAGE_TAG:-latest}
    restart: always

volumes:
  database:
    name: stocktok_db_${IMAGE_TAG:-latest}
