version: "3"

services:
  app:
    image: abbas17891/stocktok_laravel:${IMAGE_TAG:-latest}
    container_name: stocktok_app_${IMAGE_TAG:-latest}
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=stocktok_${IMAGE_TAG:-latest}
      - DB_USERNAME=root
      - DB_PASSWORD=${DB_PASSWORD:-Abbas297$}
      - APP_ENV=${IMAGE_TAG:-production}
    restart: always
    command: >
      sh -c "
        cd /app &&
        php artisan key:generate &&
        php artisan config:clear &&
        php artisan config:cache &&
        php artisan migrate &&
        php artisan serve --host=0.0.0.0 --port=8000
      "
    depends_on:
      - database

  database:
    image: mysql:8.0
    container_name: stocktok_db_${IMAGE_TAG:-latest}
    volumes:
      - database:/var/lib/mysql
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-Abbas297$}
      - MYSQL_DATABASE=stocktok_${IMAGE_TAG:-latest}
    restart: always

volumes:
  database:
    name: stocktok_db_${IMAGE_TAG:-latest}
