services:
  app:
    image: bitnami/laravel
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_DATABASE=stocktok
      - DB_USERNAME=root
      - DB_PASSWORD=Abbas297$

    restart: always

    command: >
      sh -c "
        cd /app &&
        composer install &&
        php artisan key:generate &&
        chmod -R 777 storage bootstrap/cache &&
        php artisan config:clear &&
        /opt/bitnami/scripts/laravel/run.sh
      "
