name: Deploy Laravel Application
on:
  push:
    branches:
      - main
      - staging

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_KEY }}

      - name: Set environment variables
        id: set-env
        run: |
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            echo "ENV_TAG=production" >> $GITHUB_OUTPUT
          else
            echo "ENV_TAG=staging" >> $GITHUB_OUTPUT
          fi

      - name: Build Docker image
        working-directory: backend
        run: |
          docker build --build-arg ENV=${{ steps.set-env.outputs.ENV_TAG }} -t ${{ secrets.DOCKER_USERNAME }}/stocktok_laravel:${{ steps.set-env.outputs.ENV_TAG }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/stocktok_laravel:${{ steps.set-env.outputs.ENV_TAG }} ${{ secrets.DOCKER_USERNAME }}/stocktok_laravel:latest-${{ steps.set-env.outputs.ENV_TAG }}

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/stocktok_laravel:${{ steps.set-env.outputs.ENV_TAG }}
          docker push ${{ secrets.DOCKER_USERNAME }}/stocktok_laravel:latest-${{ steps.set-env.outputs.ENV_TAG }}

  deploy-production:
    needs: build-and-push
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to production EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 35.181.171.137
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            mkdir -p ~/stocktok
            cd ~/stocktok

            # Create or update the .env file
            echo "IMAGE_TAG=production" > .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD || 'Abbas297}}" >> .env
            echo "DB_PORT=3306" >> .env

            # Download the latest docker-compose file
            curl -o docker-compose.yml https://raw.githubusercontent.com/${{ github.repository }}/main/docker-compose.yml

            # Remove old containers and images
            sudo docker-compose down
            sudo docker rmi ${{ secrets.DOCKER_USERNAME }}/stocktok_laravel:production || true
            sudo docker rmi ${{ secrets.DOCKER_USERNAME }}/stocktok_laravel:latest-production || true

            # Pull and start new containers
            sudo docker-compose pull
            sudo docker-compose up -d

  deploy-staging:
    needs: build-and-push
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to staging EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 13.37.224.245
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            mkdir -p ~/stocktok
            cd ~/stocktok

            # Create or update the .env file
            echo "IMAGE_TAG=staging" > .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD || 'Abbas297}}" >> .env
            echo "DB_PORT=3307" >> .env  # Using different port for staging

            # Download the latest docker-compose file
            curl -o docker-compose.yml https://raw.githubusercontent.com/${{ github.repository }}/staging/docker-compose.yml

            # Remove old containers and images
            sudo docker-compose down
            sudo docker rmi ${{ secrets.DOCKER_USERNAME }}/stocktok_laravel:staging || true
            sudo docker rmi ${{ secrets.DOCKER_USERNAME }}/stocktok_laravel:latest-staging || true

            # Pull and start new containers
            sudo docker-compose pull
            sudo docker-compose up -d
